### ISSUE TITLE
Acoustic grand piano sounds distorted

### ISSUE THREAD

**Issue by zoschfrosch** [gleitz/midi-js-soundfonts#35]
Hi Benjamin,

thank you for the great soundfonts. I use the MusyngKite soundfont for a virtual piano in the browser. Since your last update (14 hours ago), the acoustic grand piano sounds somewhat distorted, as if the base note was mixed with the wrong overtones. To test it, I loaded some of the .mp3 files in an audio player. Result: The distortion is in the samples.

Kind regards
Thomas

**Comment by gleitz** [comment]
Good catch! I've been playing around with a few different methods of generation and given your feedback have tweaked the script to produce a sound that does not have any distortion. I'm regenerating the audio files now and will submit a PR shortly.

My latest Soundfont comes from a 1.7GB `.sf2` file (rather than the previous 700MB version). I do notice that the new acoustic grand piano sounds slightly different from the old one, but it matches what I hear in fluidsynth and I think it sounds nice (but do let me know what you think when the new PR is up).

By the way, how are you using this repo? I always enjoy learning more about what folks are building.

**Comment by zoschfrosch** [comment]
I load your soundfont using this library: https://github.com/danigb/soundfont-player
It's part of an application for singing exercises. The singer chooses a short melody and uses it for voice warmup. The application replaces the vocal coach playing the lesson on a piano.

Thank you for fixing this issue!

Kind regards
Thomas

**Comment by gleitz** [comment]
Fix is up. It sounds really good to me ear but give it a spin

**Comment by zoschfrosch** [comment]
Thank you for the rapid fix! Indeed, the new acoustic grand piano sounds different from the old one. I'm happy that the distortion is gone. The new sound seems to have less low frequencies, sounds if you used a low cut filter. Do you use filters in your generator script? Another problem disappeared now: The very low notes had kind of a tremolo effect at the end, this disappeared now.

**Comment by zoschfrosch** [comment]
After some more tests: The new sound has more high frequencies, especially the lower notes. I like it.

**Comment by gleitz** [comment]
The last Musyng Kite I included was from a PR, so I don't know exactly how it was generated. The current generation script (fluidsynth/ogg/lame) is here -> https://github.com/gleitz/MIDI.js/blob/master/generator/ruby/soundfont_builder.rb#L405-L407

I agree that I enjoy the sound. Have you also tried the [FatBoy](https://github.com/gleitz/midi-js-soundfonts/tree/gh-pages/FatBoy) soundfont? I'd appreciate knowing which you prefer.

**Comment by zoschfrosch** [comment]
I did not yet try FatBoy...I'll give it a try and will let you know what I think about it.
